### ISSUE TITLE
Parse county and municipal-level results from 2015 general election

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-nj#1]
[Using the PDFs here](http://nj.gov/state/elections/election-information-archive-2015.html) for the general election, parse PDFs into CSV files for state legislative offices. To get municipal-level results, you'll need to use the district-by-district files ([example](http://nj.gov/state/elections/2015-results/2015-GenAssembly-gen-elect-results-1st-ld-municipality.pdf)). Include general assembly and state senate results in the same file.

You can use [Tabula](https://www.youtube.com/watch?v=of9680dgqIc) to convert the PDFs, or another tool like pdftotext.

You'll end up with two files:
- [x] County-level results (`20151201__nj__general__county.csv`)
- [x] Municipal-level results (`20151201__nj__general__municipal.csv`)

They will have the same header row, with one exception: the municipal results file will have `municipality` in addition to the following: `county`, `office`, `district`, `party`, `candidate`, `votes`

**Comment by dwillis** [comment]
Assigning to @gizm00

**Comment by gizm00** [comment]
Looks like @ssdatar has uploaded a general__county.csv - just want to confirm we don't duplicate work. @dwillis do you want me to just do the general__municipal processing?

**Comment by dwillis** [comment]
Hi @gizm00: @ssdatar was tackling the 2014 election, not 2015, so you should be clear to work on both county and municipal-level results from 2015.

**Comment by gizm00** [comment]
ah got it! thanks @dwillis

**Comment by ElectionsNerd** [comment]
I will take this.

**Comment by acolter** [comment]
I'll start working on these.

**Comment by acolter** [comment]
There are a couple of discrepancies in the original pdf files. 
- Sam Fiocchi, Cape May, District 1 has 9,495 votes in the municipal file vs. 9475 in the county file
- Fran Zimmer, Burlington, District 9 has 396 votes in the municipal file vs. 406 in the county file
