### ISSUE TITLE
Parse county-level results from 2014 general election

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-nj#2]
Using Tabula and the PDFs for [U.S. Senate](http://nj.gov/state/elections/2014-results/2014-official-general-results-us-senate.pdf), [U.S. House](http://nj.gov/state/elections/2014-results/2014-official-general-results-us-house.pdf) & [U.S. House special](http://nj.gov/state/elections/2014-results/2014-official-general-results-special-us-house.pdf) elections, extract county-wide results into a CSV file called `20141104__nj__general__county.csv`.

**Comment by ssdatar** [comment]
I am working on this
