### ISSUE TITLE
County-level results for primary elections

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-nj#36]
[Using the PDFs here](https://nj.gov/state/elections/election-information-archive.html) for primary elections, parse PDFs into CSV files for president, U.S. Senate, U.S. House and state legislative offices. Include the voter turnout PDF for registered voters and ballots cast.

The office names should be: `President`, `U.S. Senate`, `U.S. House`, `State Senate`, and `General Assembly`. Include the district numbers for the last three offices.

You can use [Tabula](https://www.youtube.com/watch?v=of9680dgqIc) to convert the PDFs, or another tool like pdftotext.

You'll end up with these files:
- [x] `20180605__nj__primary__county.csv`
- [x] `20170605__nj__primary__county.csv`
- [x] `20150602__nj__primary__county.csv`
- [x] `20140603__nj__primary__county.csv`
- [x] `20130604__nj__primary__county.csv`
- [x] `20120605__nj__primary__county.csv`
- [x] `20110607__nj__primary__county.csv`
- [x] `20100608__nj__primary__county.csv`

The county-level file will have a header row like this: `county`, `office`, `district`, `party`, `candidate`, `votes`

**Comment by acolter** [comment]
Working on these.
