### ISSUE TITLE
Parse 2018 General Election Results by County and Municipality

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-nj#38]
[Using the PDFs here](http://www.nj.gov/state/elections/election-information-archive-2018.html#general) for the general election, parse PDFs into CSV files for president, U.S. House and state legislative offices.

You can use [Tabula](https://www.youtube.com/watch?v=of9680dgqIc) to convert the PDFs, or another tool like pdftotext.

You'll end up with these files:
- [x] County-level results (`20191106__nj__general__county.csv`)
- [x] Municipal-level results (`20181106__nj__general__municipal.csv`)

The county-level file will have a header row like this: `county`, `office`, `district`, `party`, `candidate`, `votes`

The municipal-level file will have a header row like this: `county`, `municipality`, `office`, `district`, `party`, `candidate`, `votes`

**Comment by acolter** [comment]
Working on these.
