### ISSUE TITLE
Salem County 2018 General Precinct Results

### ISSUE THREAD

**Issue by joshuakalla** [openelections/openelections-data-nj#41]
The 2018 general results from Salem appear to be at the town level (e.g., Alloway, Elmer, see https://github.com/openelections/openelections-sources-nj/blob/master/2018/Salem%20NJ%20OfficialStatementofVoteSummary11-06-2018.pdf) while the 2016 results break down further by precinct (e.g., Alloway District 2, Elmer District 1, see https://github.com/openelections/openelections-sources-nj/blob/master/2016/Salem/2016-General-SOV.pdf).

Do you know if Salem will be producing a disaggregated file for 2018?

**Comment by dwillis** [comment]
@joshuakalla We'll ask.

**Comment by joshuakalla** [comment]
I just got this attached from the county. Do you have a good way to parse the lovely file they sent? Or is there a way for me to help? 

[Election 2018 General Unofficial Statement of Vote by precinct (11-6-2018).pdf](https://github.com/openelections/openelections-data-nj/files/3291588/Election.2018.General.Unofficial.Statement.of.Vote.by.precinct.11-6-2018.pdf)

**Comment by dwillis** [comment]
@joshuakalla Yeah, we got the same file. I'm double-checking with the county because this is clearly marked as unofficial and appears to have been generated on election night.

**Comment by joshuakalla** [comment]
I got this file today from Edward J Meschi, Special Deputy Clerk, at Salem. Is this what you need? It is marked Official.

[2018GENERALELECTIONdoc01718420181220160156.pdf](https://github.com/openelections/openelections-data-nj/files/3298811/2018GENERALELECTIONdoc01718420181220160156.pdf)

**Comment by dwillis** [comment]
@joshuakalla Thanks - we're on it.

**Comment by dwillis** [comment]
@joshuakalla This is fixed now. Thanks!

**Comment by joshuakalla** [comment]
Thank you!
