### ISSUE TITLE
Parse 2016 General Election Results by County and Municipality

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-nj#6]
[Using the PDFs here](http://www.nj.gov/state/elections/election-information-archive-2016.html#general) for the general election, parse PDFs into CSV files for president, U.S. House and state legislative offices.

You can use [Tabula](https://www.youtube.com/watch?v=of9680dgqIc) to convert the PDFs, or another tool like pdftotext.

You'll end up with these files:
- [x] County-level results (`20161108__nj__general.csv`)
- [x] Municipal-level results (`20161108__nj__general__municipal.csv`)

The county-level file will have a header row like this: `county`, `office`, `district`, `party`, `candidate`, `votes`

The municipal-level file will have a header row like this: `county`, `municipality`, `office`, `district`, `party`, `candidate`, `votes`

**Comment by cholq** [comment]
I will go ahead and work on the county and municipal files

**Comment by cholq** [comment]
@dwillis I see for some of the other states, there is an openelection-sources-XX repo that stores the PDFs that are downloaded from the states at the start of the process.  I don't see a "sources" repo for NJ.  Is that necessary for NJ, or do you only create those in specific circumstances?

**Comment by dwillis** [comment]
We usually use the sources repos for PDFs and other documents that aren't posted online, so we don't have one yet for NJ but I'm not opposed to it.

**Comment by cholq** [comment]
I was just looking for a reason why they existed for some states and not others.  If it gets created for NJ, I'll populate it, but if it doesn't, that doesn't bother me.

**Comment by dwillis** [comment]
Here we go: https://projects.propublica.org/itemizer/committee/C00075820/reports/FEB%20MONTHLY

**Comment by cholq** [comment]
I see the 2014 general election only has county-level data so far.  I'll work on the municipal file for the 2014 general election next.
